spring.application.name=SpringBootJPA_Day_14

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=org.h2.Driver

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb
spring.datasource.username=root
spring.datasource.password=Venu@1526
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true