spring.application.name=SpringBootJDBC_Day12


spring.datasource.username = root
spring.datasource.url = jdbc:mysql://localhost:3306/springbootdb
spring.datasource.password =Venu@1526
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver